# Site settings
title: "SixFifty"
description: ""
baseurl: "" # Should be the path-prefix on the domain
url: "https://sixfifty.org.uk" # Should be the domain
author: "SixFifty Contributors"

# Social media
twitter_username: SixFiftyData
github_username: six50
facebook_username: SixFiftyData
medium_username: SixFiftyData
instagram_username: sixfiftydata

# Build settings
kramdown:
  input: GFM
permalink: pretty
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - webpack.config.js
  - package.json
  - README.md
  - node_modules
  - _frontend

# Third-party services
# just leave empty to disable it
google_analytics: UA-97912333-1
disqus_shortname:
