# Site settings
title: "Six50"
description: ""
baseurl: ""
url: ""
author: "Six50"

# Build settings
kramdown:
  input: GFM
permalink: pretty
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname:
