# Site settings
title: "SixFifty"
description: ""
baseurl: ""
url: "http://sixfifty.org.uk"
author: "SixFifty Contributors"

# Build settings
kramdown:
  input: GFM
permalink: pretty
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - webpack.config.js
  - package.json
  - README.md

# Third-party services
# just leave empty to disable it
google_analytics: UA-97912333-1
disqus_shortname:
