# Site settings
title: "Six50"
description: ""
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "" # default is empty
author: "Six50"

# Build settings
kramdown:
  input: GFM
permalink: pretty
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname:
